//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinesApiProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fines
    {
        public int Id { get; set; }
        public string studentname { get; set; }
        public Nullable<System.DateTime> dateoffine { get; set; }
        public string status { get; set; }
        public Nullable<int> rule_id { get; set; }
    
        public virtual FineRules FineRules { get; set; }
    }
}
